/// Simulated bets from the backtest harness, one row per bet per run.
/// Each run is a separate experiment: filter to one run before adding them up.
table 'Backtest Bets'
	lineageTag: 75953be6-4ad3-41d0-abfb-671741d7e75f

	column Run
		dataType: string
		lineageTag: 2333b725-9764-483b-90f5-187a9925fde2
		summarizeBy: none
		sourceColumn: run

	column Period
		dataType: string
		lineageTag: 82768774-8afa-4084-887d-f62042e03c44
		summarizeBy: none
		sourceColumn: period

	column Strategy
		dataType: string
		lineageTag: 1e15ad7a-95ab-4dc8-88c8-a63907444966
		summarizeBy: none
		sourceColumn: strategy

	column Side
		dataType: string
		lineageTag: 266f0b08-2947-4b7c-86b5-6a26f980aa02
		summarizeBy: none
		sourceColumn: side

	column 'Station ID'
		dataType: string
		isHidden
		lineageTag: ee5d45ec-58f5-412c-a6ce-743a483d865b
		summarizeBy: none
		sourceColumn: station_id

	column 'Market Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 553fd69f-d8ac-4ccf-bce1-34c1f424f1d1
		summarizeBy: none
		sourceColumn: market_date

	column Bracket
		dataType: string
		lineageTag: 8d0868b4-3a83-46b5-b158-8c09787b28c9
		summarizeBy: none
		sourceColumn: bracket_label

	column 'Model Probability'
		dataType: double
		formatString: 0.0%
		lineageTag: 2094307b-1b28-42ad-85b0-714d02cf3098
		summarizeBy: none
		sourceColumn: claimed_p

	column 'Entry Price'
		dataType: double
		formatString: 0.000
		lineageTag: 3348a593-839a-477c-90e1-4c018c45bf06
		summarizeBy: none
		sourceColumn: entry_price

	column 'Fill Price'
		dataType: double
		formatString: 0.000
		lineageTag: 8f7892ae-f7e9-4343-9170-d96e47407477
		summarizeBy: none
		sourceColumn: fill_vwap

	column Stake
		dataType: double
		formatString: \$#,0.00
		lineageTag: 0b65d8e8-3a31-463d-a708-8e335a0af865
		summarizeBy: none
		sourceColumn: stake

	column Won
		dataType: boolean
		lineageTag: f2867ba6-7890-4fdc-9b91-a10941e03890
		summarizeBy: none
		sourceColumn: won

	column P&L
		dataType: double
		formatString: \$#,0.00;-\$#,0.00;\$#,0.00
		lineageTag: 46e88ce9-ee9a-4ee7-98db-2d0be741392d
		summarizeBy: none
		sourceColumn: pnl

	column 'Entry Time'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 211c6f75-6d30-4979-8d01-42a9e1672f0b
		summarizeBy: none
		sourceColumn: entry_time

	column 'Exit Reason'
		dataType: string
		lineageTag: 79b3c3be-806a-4692-9197-22a1e4b89d1d
		summarizeBy: none
		sourceColumn: exit_reason

	partition 'Backtest Bets' = m
		mode: import
		source =
				let
				    RunNames = [
				        champion_l2_delayed_oos_bd = "Champion, delayed entry: out-of-sample B-D",
				        champion_l2_delayed_fixed = "Champion, delayed entry: fixed A-D",
				        champion_l2_immediate_oos_bd = "Champion, immediate entry: out-of-sample B-D",
				        champion_l2_immediate_fixed = "Champion, immediate entry: fixed A-D",
				        candidate_l2_depth_train = "Candidate L2 depth: train",
				        candidate_l2_depth_test = "Candidate L2 depth: test"
				    ],
				    Files = Folder.Files(ProjectFolder & "\backtest\results\bets"),
				    ParquetFiles = Table.SelectRows(Files, each [Extension] = ".parquet"),
				    WithRun = Table.AddColumn(
				        ParquetFiles,
				        "run",
				        each Record.FieldOrDefault(RunNames, Text.BeforeDelimiter([Name], "."), [Name]),
				        type text
				    ),
				    WithBets = Table.AddColumn(WithRun, "bets", each Parquet.Document([Content])),
				    Bets = Table.ExpandTableColumn(
				        Table.SelectColumns(WithBets, {"run", "bets"}),
				        "bets",
				        {
				            "period", "strategy", "side", "station_id", "market_date", "bracket_label",
				            "claimed_p", "entry_price", "fill_vwap", "stake", "won", "pnl",
				            "entry_ts", "exit_reason"
				        }
				    ),
				    WithEntryTime = Table.AddColumn(
				        Bets,
				        "entry_time",
				        each #datetime(1970, 1, 1, 0, 0, 0) + #duration(0, 0, 0, [entry_ts]),
				        type datetime
				    ),
				    Typed = Table.TransformColumnTypes(
				        Table.RemoveColumns(WithEntryTime, {"entry_ts"}),
				        {
				            {"period", type text}, {"strategy", type text}, {"side", type text},
				            {"station_id", type text}, {"market_date", type date},
				            {"bracket_label", type text}, {"claimed_p", type number},
				            {"entry_price", type number}, {"fill_vwap", type number},
				            {"stake", type number}, {"won", type logical}, {"pnl", type number},
				            {"exit_reason", type text}
				        },
				        "en-US"
				    )
				in
				    Typed

