/// Day-ahead forecast of the daily high against the observed high,
/// one row per station, day and weather model.
table Forecasts
	lineageTag: 6425d51f-6b21-461d-a5a1-ddc6e6fd988c

	column 'Station ID'
		dataType: string
		isHidden
		lineageTag: 290aab6d-4121-4223-a071-46b09f16e211
		summarizeBy: none
		sourceColumn: station_id

	column 'Target Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5514bdeb-ae3c-4075-b374-b234d06e5b56
		summarizeBy: none
		sourceColumn: target_date

	column Model
		dataType: string
		lineageTag: c740d753-6883-4ff3-bd2f-bca339ce71c6
		summarizeBy: none
		sourceColumn: model

	column 'Ensemble Members'
		dataType: int64
		formatString: 0
		lineageTag: 24710a62-a41e-4d47-8303-7c5f681aa8b2
		summarizeBy: none
		sourceColumn: ensemble_members

	column 'Forecast High (°C)'
		dataType: double
		formatString: 0.0
		lineageTag: a45b59b7-e751-4f92-b9a5-4b0c8e1d7bd9
		summarizeBy: none
		sourceColumn: forecast_high_c

	column 'Observed High (°C)'
		dataType: double
		formatString: 0.0
		lineageTag: f594bbcb-7c4d-473a-a90a-6b0e85bee178
		summarizeBy: none
		sourceColumn: observed_high_c

	column 'Error (°C)'
		dataType: double
		formatString: 0.0
		lineageTag: e71f87d9-85e9-45c2-a89d-a1c9853f0e16
		summarizeBy: none
		sourceColumn: error_c

	partition Forecasts = m
		mode: import
		source =
				let
				    Source = Parquet.Document(
				        File.Contents(ProjectFolder & "\powerbi\data\fact_forecast_error.parquet")
				    ),
				    Typed = Table.TransformColumnTypes(
				        Source,
				        {
				            {"station_id", type text}, {"target_date", type date}, {"model", type text},
				            {"ensemble_members", Int64.Type}, {"forecast_high_c", type number},
				            {"observed_high_c", type number}, {"error_c", type number}
				        },
				        "en-US"
				    ),
				    ModelNames = [
				        bom_access_global = "BOM ACCESS (Australia)",
				        dmi_seamless = "DMI (Denmark)",
				        ecmwf_ifs025 = "ECMWF IFS (Europe)",
				        gem_seamless = "GEM (Canada)",
				        gfs_seamless = "GFS (US)",
				        icon_seamless = "ICON (Germany)",
				        jma_seamless = "JMA (Japan)",
				        knmi_seamless = "KNMI (Netherlands)",
				        meteofrance_seamless = "ARPEGE (France)",
				        ncep_gfs013 = "GFS 0.13° (US)",
				        ukmo_seamless = "UKMO (UK)"
				    ],
				    Renamed = Table.TransformColumns(
				        Typed,
				        {{"model", each Record.FieldOrDefault(ModelNames, _, _), type text}}
				    )
				in
				    Renamed

